---
- name: Install and configure Docker and Kubernetes
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Ensure python3-apt is installed
      ansible.builtin.apt:
        name: python3-apt
        state: present
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: yes

    # Kubernetes installation
    - name: Install dependencies for Kubernetes
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Kubernetes GPG key
      ansible.builtin.apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
        state: present

    - name: Add Kubernetes repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
        state: present

    - name: Update apt cache after adding Kubernetes repo
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Kubernetes components
      ansible.builtin.apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

    - name: Hold Kubernetes packages to prevent automatic updates
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Enable kubelet service
      ansible.builtin.systemd:
        name: kubelet
        enabled: yes

    - name: Configure containerd for Kubernetes
      ansible.builtin.shell: |
        sudo mkdir -p /etc/containerd
        containerd config default | sudo tee /etc/containerd/config.toml
        sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
        sudo systemctl restart containerd

    - name: Initialize Kubernetes cluster (single-node)
      ansible.builtin.shell: |
        sudo kubeadm init --pod-network-cidr=10.244.0.0/16
        mkdir -p /home/ubuntu/.kube
        sudo cp -i /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
        sudo chown ubuntu:ubuntu /home/ubuntu/.kube/config

    - name: Remove taint from master node (for single-node cluster)
      ansible.builtin.shell: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
      become_user: ubuntu

    - name: Install Flannel CNI plugin
      ansible.builtin.shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      become_user: ubuntu